# Service name
serviceName: skill-assessment

# API port number
serverPort: 8084

# database information
database:
  host: localhost
  port: 27017
  name: skill_assessment
  user: mongo
  password: mongo
  connectionString: mongodb://localhost:27017/

jwt: 
  # Secret key used to create the signature
  secret: t%682@#90

  # Token expiry time in minutes
  expiryTime: 30

# CORS
corsOptions:
  origin: '*'
  debug: false

# Enable sign in 
user:
  keepSigned: true

